### ISSUE TITLE
Unusual stdin for input in python/08

### ISSUE THREAD

**Issue by yackx** [ChrisPenner/Advent-Of-Code-Polyglot#70]
For day 8 in python, the input is read from `stdin`, unlike all previous puzzles where `input.txt` file is used.

As a result, the program behaves as if it was stuck, while it is actually waiting for user input.

Fix suggestion: read from `input.txt` to be consistent.

**Comment by ChrisPenner** [comment]
Fixed in https://github.com/ChrisPenner/Advent-Of-Code-Polyglot/commit/f4541b467575c6826d82608e1d009d3e54416953
